export enum FILE_EXTENSION {
  JS = 'js',
  ICO = 'ico',
  CSS = 'css',
  PNG = 'png',
  JPG = 'jpg',
  JPEG = 'jpeg',
  WOFF2 = 'woff2',
  WOFF = 'woff',
  TTF = 'ttf',
  SVG = 'svg',
  MP4 = 'mp4',
  MP3 = 'mp3',
  GIF = 'gif',
  TXT = 'txt',
  HTML = 'html',
  CSV = 'csv',
  XML = 'xml',
  PDF = 'pdf'
}